# Generated by Django 3.2.7 on 2021-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extn', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField(max_length=4)),
                ('destination', models.CharField(max_length=100)),
                ('is_official', models.BooleanField(default=True)),
                ('is_international', models.BooleanField(default=True)),
                ('time_booked', models.DateTimeField()),
                ('time_connected', models.DateTimeField()),
                ('time_finished', models.DateTimeField()),
                ('remark', models.CharField(max_length=20)),
            ],
        ),
    ]
