# Generated by Django 3.2.7 on 2021-09-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20210907_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='name',
            new_name='fullname',
        ),
    ]
