# Generated by Django 3.2.7 on 2021-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_rename_name_calllog_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='time_booked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='time_connected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='time_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
