# Generated by Django 3.2.7 on 2021-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20210922_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='budget',
            field=models.CharField(max_length=20),
        ),
    ]
